---
title: "Acotaci√≥n de Isometr√≠a en vistas 3D"
author: "Bryan Espinoza"
publishedAt: "2022-03-13"
summary: "Crear acotacion de tuber√≠as en vistas de isometr√≠a 3D."
tags:
  - "üíª Desarrollo"
  - "Revit API"
---

El siguiente aplicativo a desarrollar tiene como objetivo generar las cotas de manera autom√°tica en una vista isom√©trica 3D.

Iniciaremos creando un nuevo proyecto en Visual Studio al cual nombraremos **CotasThreeD,** para Autodesk Revit 2020.

Nuestro proyecto seguir√° los mismos pasos de la publicaci√≥n de¬†[**Mi primer addin con la API de Revit**](https://lambda.com.pe/blog/mi-primer-addin)¬†con la √∫nica diferencia en el nombre del proyecto, del cual tendr√≠amos el siguiente c√≥digo.

```csharp:CotasThreeD.cs
#region NAMESPACES
using Autodesk.Revit.Attributes;
using Autodesk.Revit.DB;
using Autodesk.Revit.DB.Plumbing;
using Autodesk.Revit.UI;
using Autodesk.Revit.UI.Selection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

#endregion

namespace CotasThreeD
{
   public class CotasThreeD : IExternalCommand
   {
      public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elements)
      {
         throw new NotImplementedException();
      }
   }
}
```

Luego accederemos a la variable [**Documento**](https://www.revitapidocs.com/2022/ab1718f9-45fb-b3d3-827e-32ff81cf929c.htm), para poder trabajar con propiedades y m√©todos a lo largo de nuestro proyecto.

```csharp:CotasThreeD.cs
// Obtenci√≥n de variables
   UIApplication uiApp = commandData.Application;
   UIDocument uiDoc = uiApp.ActiveUIDocument;
   Document doc = uiDoc.Document;
```

Para seleccionar elementos utilizaremos el **PickObjects** y generaremos una lista de referencias.

```csharp:CotasThreeD.cs
// Seleccionar elementos
   IList<Reference> pickreferences = uiDoc.Selection
                                          .PickObjects(ObjectType.Element,
														"Select element");
```

Generaremos una condicional **Foreach** para recorrer todos los elementos

```csharp:CotasThreeD.cs
// Recorro todos los elementos
   foreach (Reference elementref in pickreferences)
```

Luego obtendremos el **ElementId** para as√≠ filtrarlos y trabajar solo con las categor√≠as de tuber√≠as

```csharp:CotasThreeD.cs
// Obtengo el ElementId desde la referencia
   ElementId pipeElementId = elementref.ElementId;


// Condicional (Filtrar los elementos para trabajar solo con tuber√≠as)
   Element pipeElement = doc.GetElement(pipeElementId);
   if ((BuiltInCategory)pipeElement.Category.Id.IntegerValue != BuiltInCategory.OST_PipeCurves){
      continue;
   }

// Continue; funciona para omitir los procesos siguientes y continuar con el siguiente elemento en la lista.

// Obtener elemento doc.GetElement(pipeElementId), pero lo voy a convertir en un Pipe
   Pipe pipe = doc.GetElement(pipeElementId) as Pipe;
```

Ahora obtendremos la curva de localizaci√≥n, a su vez el punto de inicio y fin.

```csharp:CotasThreeD.cs
// Obtengo la curva, pero primero tengo que obtener la location curve
   LocationCurve pipeLocationCurve = pipe.Location as LocationCurve;

// Obtengo la curva
   Curve pipeCurve = pipeLocationCurve.Curve;

// Obtengo punto inicio y punto fin
   XYZ startPipeCurvePoint = pipeCurve.GetEndPoint(0); // 0: Inicio
   XYZ endPipeCurvePoint = pipeCurve.GetEndPoint(1); // 1: final
```

A partir de dos puntos obtenemos una linea con el m√©todo **CreateBound**.

```csharp:CotasThreeD.cs
// Dos puntos son necesarios para crear una linea
   Line line = Line.CreateBound(startPipeCurvePoint, endPipeCurvePoint);
```

Luego crearemos un plano de trabajo con **CreateByThreePoints** para crearlos en tres puntos (x, y, z).

```csharp:CotasThreeD.cs
Plane plane = Plane.CreateByThreePoints(startPipeCurvePoint,
                                       endPipeCurvePoint,
                                       new XYZ(0, 0, endPipeCurvePoint.Z));
```

Luego creamos un Array de referencias vac√≠as donde recorreremos las geometr√≠as de la tuber√≠a, y crearemos una condicional donde si la tuber√≠a es diferente de nula nos cree opciones de geometr√≠as y le calcule las referencias dentro de la vista activa.

```csharp:CotasThreeD.cs
// Lista vac√≠a para obtener las referencias
ReferenceArray references = new ReferenceArray();

// Llenar esas referencias (Lista)
if (pipe != null)
{
  // Configurar opciones de geometr√≠a
  Options op = doc.Application.Create.NewGeometryOptions();
  op.ComputeReferences = true;
  op.View = doc.ActiveView;
  op.IncludeNonVisibleObjects = true;

  Reference R1 = null; // referencia del punto inicial
  Reference R2 = null; // referencia del punto final

  // recorrer la geometr√≠a tratando de obtener la curva
  foreach (var geoObj in pipe.get_Geometry(op))
  {
		// pedimos que la geometr√≠a sea una curva
		Curve c = geoObj as Curve;
		if (c != null)
		{
		   R1 = c.GetEndPointReference(0);
		   R2 = c.GetEndPointReference(1);
		}
   }
   references.Append(R1);
   references.Append(R2);
}

```

Ahora iniciaremos nuestra **transaction**, luego definiremos y crearemos un plano de trabajo mediante un **SketchPlane.**

```csharp:CotasThreeD.cs
using (Transaction trans = new Transaction(doc))
   {
     trans.Start("Create Lines");

      // Creamos el plano de trabajo
      SketchPlane sp = SketchPlane.Create(doc, plane);
      // Establecemos el plano de trabajo
      uiDoc.Document.ActiveView.SketchPlane = sp;

      //.....
   }
```

Por √∫ltimo creamos la cota, indicando que se generara en la vista activa.

```csharp:CotasThreeD.cs
{
   //.....

	// M√©todo para crear una nueva dimensi√≥n
	Dimension dimension = doc.Create.NewDimension(doc.ActiveView, line, references);
   // Commit de los cambios
	trans.Commit();
}
```

Ya llegado a este punto hemos culminado con el aplicativo, ahora para generar el v√≠nculo entre la (.dll) y Revit, tenemos que generar el archivo manifiesto y agregar los eventos de compilaci√≥n.

```xml:CotasThreeD.addin
<?xml version="1.0" encoding="utf-8"?>
<RevitAddIns>
	<AddIn Type="Command">
		<Assembly>CotasThreeD.dll</Assembly>
		<ClientId>e625b384-c38e-4b72-96fd-f1af6e98565f</ClientId>
		<FullClassName>CotasThreeD.CmdCotasThreeD</FullClassName>
		<Text>CotasThreeD</Text>
		<Description>Un simple addin para acotar isometrias 3D</Description>
		<VisibilityMode>AlwaysVisible</VisibilityMode>
		<VendorId>ADSK</VendorId>
		<VendorDescription>Lambda Ingenieria e Innovacion</VendorDescription>
	</AddIn>
</RevitAddIns>
```

Es un proceso que vale la pena intentarlo y probarlo, sum√©monos todos para poder formar una comunidad de personas que tengan las ganas de ingresar a este nuevo mundo de la programaci√≥n.

![Eventos de Compilaci√≥n.PNG](/images/posts/acotacion-isometria-3d/demostracion.gif)

### Nuestras redes sociales

Si necesitan m√°s informaci√≥n sobre este incre√≠ble mundo de la automatizaci√≥n de procesos a trav√©s de la creaci√≥n de aplicaciones en Autodesk Revit no duden en escribirme a mi LinkedIn¬†[Bryan Espinoza Allcca](https://www.linkedin.com/in/bryan-espinoza-bim/)¬†o dejar comentarios debajo de este post.

üì∑ Instagram : https://www.instagram.com/rivers_code <br />
üìì Blog : https://lambda.com.pe/blog <br />
üåê Web : https://lambda.com.pe <br />
‚≠ê Facebook : https://www.facebook.com/LambdaInnovacion <br />
‚úîÔ∏è Tiktok : https://www.tiktok.com/@lambda.innovacion <br />
